config/routes.rb
Lyrical::Application.routes.draw do
  root to: 'articles#index'
  resources :tags
  resources :authors
  resources :articles do
    resources :comments
  end
  match '/auth/:provider/callback', to: 'sessions#create', via: :get
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings

	def tag_list=(tags_string)
	  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
	  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
	  self.tags = new_or_found_tags
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
def self.find_or_create_by_auth(auth_data)
  find_or_create_by_provider_and_uid(auth_data["provider"], auth_data["uid"],
                                     name: auth_data["info"]["name"])
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end
	def new
		@article =Article.new
	 @comment =Comment.new
	end
	def create
	  @article = Article.new(article_params)
	  @article.save
	  flash.notice = "Article '#{@article.title}' updated!"
	  redirect_to article_path(@article)
	end
	def article_params
      params.require(:article).permit(:title, :body, :tag_list)
	end
	def destroy
		@article = Article.find(params[:id])
		@article.delete
		flash.notice = "Article '#{@article.title}' updated!"
		redirect_to articles_path
	end
	def edit 
		@article = Article.find(params[:id])
	end
	def update
	  @article = Article.find(params[:id])
	  @article.update(article_params)
	  flash.notice = "Article '#{@article.title}' updated!"
	  redirect_to article_path(@article)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @article = Article.find(params[:article_id])
    @comment =Comment.new
  end

  def index
    @comments = Comment.all
  end

	def create
	  @comment = Comment.create(comment_params)
	  @comment.article_id = params[:article_id]

	  @comment.save

	  redirect_to article_path(@comment.article)
	end

  #def update
   # @comment = Comment.find(params[:id])
   # @comment.update(comment_params)
   # flash.notice = "Comment updated!"
  #  redirect_to comments_path(@comment)
 # end

	def comment_params
	  params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    render text: request.env["omniauth.auth"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :line1 %><br>
    <%= f.text_field :line1 %>
  </div>
  <div class="field">
    <%= f.label :line2 %><br>
    <%= f.text_field :line2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :user_id => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <thead>
    <tr>
      <th>Line1</th>
      <th>Line2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.line1 %></td>
        <td><%= address.line2 %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.zip %></td>
        <td><%= address.user_id %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line1:</strong>
  <%= @address.line1 %>
</p>

<p>
  <strong>Line2:</strong>
  <%= @address.line2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @address.zip %>
</p>

<p>
  <strong>User:</strong>
  <%= @address.user_id %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :Piece %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/comment.html.erb
<%= form_for(@comment) do |f| %>
  <ul>
  <% @comment.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>


  <p>
    <%= f.label :name %><br />
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit a Piece</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Lyrics</h1>

<ul id="articles"> 
  <% @articles.each do |article| %> 
    <li> 
      <%= link_to article.title, article_path(article), class: 'article_title' %> 
    </li> 
  <% end %> 
</ul> 

  <%= link_to "Create a New Piece", new_article_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>Create a New Piece</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><center>
    <b><%= @article.title %></b>
        <br> </br>
       <div align="left"> <%= @article.body %></div>

    <br> </br>

    <%= link_to "Edit", edit_article_path(@article) %>
    <%= link_to "Delete", article_path(@article), method: :delete, confirm: "Are you sure?" %>
    <%= link_to "Back to Articles List", articles_path %>

    <%= link_to "Comment", new_article_comment_path(@article), class: "top-button" %>

    </center></p>

<h3>Comments (<%= @article.comments.size %>)</h3>
<p><%= @article.save %></p>
<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %><%= link_to "<< Back to Lyrics List", articles_path %>
<%= link_to "delete", article_path(@article), method: :delete, confirm: "Really delete the piece?" %>
<%= link_to "edit", edit_article_path(@article) %>

app/views/comments/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
<p>
  <%= f.label :author_name, "Your Name" %><br/>
  <%= f.text_field :author_name %>
</p>
<p>
  <%= f.label :body, "Your Comment" %><br/>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit 'Submit' %>
</p>
<% end %>

app/views/comments/new.html.erb
<h1>Create a Comment</h1>
<%= render partial: 'comments/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lyrical</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="flash"><%= flash.notice %></p>

  <%= yield %>

</body>
</html>